root: true
env:
  browser: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
ignorePatterns:
  - dist
parser: '@typescript-eslint/parser'
plugins:
  - react-refresh
rules:
  'react-refresh/only-export-components':
    - warn
    - allowConstantExport: true
