root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - prettier
env:
  es2020: true
  browser: true
ignorePatterns:
  - dist
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
  tsconfigRootDir: .
plugins:
  - react-refresh
rules:
  "react-refresh/only-export-components":
    - warn
    - allowConstantExport: true
settings:
  react:
    version: "detect"
