root: true
env:
  node: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
  tsconfigRootDir: .
